# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Landon Melton"

# A description of your site for meta tag, search engine results.
description: "This site is a collection of the hobbies and life of Landon Melton."

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: ""

# Favicon
favicon: images/favicon1.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: "G-BGTJ3HJF3S"

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: 
  - text: About
    url: /about/
  - text: Manuals
    url: /style-guide/
  - text: Life
    url: /tags/
  - text: Treat
    url: https://www.youtube.com/watch?v=dQw4w9WgXcQ

# Colors
accent_color: '#FFD700'

# Site footer
footer:
  content: "&copy; Parker-Meltons all rights reserved. Thank you for visiting Landon's Life."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 4
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
